export const api_root_url = "https://api.coinmarketcap.com";

export const colors = ["red", "blue", "green", "yellow", "grey", "orange", "pink", "black"];

export const FETCHING_COIN_DATA = "FETCHING_COIN_DATA";
export const FETCH_COIN_DATA_SUCESS = "FETCH_COIN_DATA_SUCESS";
export const FETCH_COIN_DATA_ERR = "FETCH_COIN_DATA_ERR";

export const FILTER_TEXT = "FILTER_TEXT";
export const SORT_BY = "SORT_BY";



export const RESET_STATE = "RESET_STATE";

export const EMAIL_CHANGED = "EMAIL_CHANGED";
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";

export const  REQUEST_LOGIN_USER = "REQUEST_LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const  LOGIN_USER_FAIL = " LOGIN_USER_FAIL";


export const  REQUEST_LOGOUT_USER = "REQUEST_LOGOUT_USER";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const  LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";


export const REQUEST_SIGNUP_USER = "REQUEST_SIGNUP_USER";
export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FAIL = "SIGNUP_USER_FAIL";


export const IS_USER_LOGGED_IN = "IS_USER_LOGGED_IN";


export const FETCHING_ALL_COIN_DATA = "FETCHING_ALL_COIN_DATA";
export const FETCH_ALL_COIN_DATA_SUCESS = "FETCH_ALL_COIN_DATA_SUCESS";
export const FETCH_ALL_COIN_DATA_ERR = "FETCH_ALL_COIN_DATA_ERR";


export const ADD_COINS_TO_WATCH_LIST = "ADD_COINS_TO_WATCH_LIST";
export const ADD_COINS_TO_WATCH_LIST_SUCCESS = "ADD_COINS_TO_WATCH_LIST_SUCCESS";
export const ADD_COINS_TO_WATCH_LIST_ERR = "ADD_COINS_TO_WATCH_LIST_ERR";

export const FETCH_WATCHED_COINS_SUCCESS = "FETCH_WATCHED_COINS_SUCCESS";